pub fn build() -> tauri::Builder<tauri::Wry> {
    tauri::Builder::default()
        .plugin(tauri_plugin_store::Builder::new().build())
        .invoke_handler(tauri::generate_handler![
            crate::commands::auth::load_desktop_auth_token,
            crate::commands::auth::save_desktop_auth_token,
            crate::commands::image_classifier::check_image_classifier_environment,
            crate::commands::image_classifier::select_image_classifier_inputs,
            crate::commands::image_classifier::select_image_classifier_output_path,
            crate::commands::image_classifier::discover_image_classifier_inputs,
            crate::commands::image_classifier::stop_image_classifier,
            crate::commands::image_classifier::run_image_classifier_stream,
            crate::commands::image_classifier::run_image_classifier,
            crate::commands::image_classifier::image_classifier_action,
            crate::commands::image_classifier::image_classifier_result_action,
            crate::commands::minecraft_server::query_minecraft_server,
            crate::commands::minecraft_server_storage::read_minecraft_server_storage,
            crate::commands::minecraft_server_storage::write_minecraft_server_storage,
            crate::commands::widget::sync_widget_auth_token
        ])
}
