"""系统模型兼容入口。"""

from app.modules.system.models import (
    SYSTEM_SETTING_COMMENTS_ENABLED,
    SYSTEM_SETTING_COMMENTS_MIN_ROLE,
    SYSTEM_SETTING_COMMENTS_STEALTH,
    SYSTEM_SETTING_REGISTER_ENABLED,
    SystemSetting,
)

__all__ = [
    "SYSTEM_SETTING_COMMENTS_ENABLED",
    "SYSTEM_SETTING_COMMENTS_MIN_ROLE",
    "SYSTEM_SETTING_COMMENTS_STEALTH",
    "SYSTEM_SETTING_REGISTER_ENABLED",
    "SystemSetting",
]
