"""文件操作兼容入口。"""

from app.modules.files.operations import (
    build_archive_payload,
    create_folder,
    delete_file,
    delete_folder,
    move_file,
    move_folder,
    rename_file,
    rename_folder,
    resolve_storage_directory,
    should_compress_static_images,
    upload_article_image,
    upload_file,
    upload_file_for_purpose,
    validate_upload_purpose,
    最大上传字节数,
    普通文件存储目录,
    文章图片存储目录,
)

__all__ = [
    "build_archive_payload",
    "create_folder",
    "delete_file",
    "delete_folder",
    "move_file",
    "move_folder",
    "rename_file",
    "rename_folder",
    "resolve_storage_directory",
    "should_compress_static_images",
    "upload_article_image",
    "upload_file",
    "upload_file_for_purpose",
    "validate_upload_purpose",
    "最大上传字节数",
    "普通文件存储目录",
    "文章图片存储目录",
]
