"""账单 Schema 兼容入口。"""

from app.modules.bills.schemas import (
    BillAccountCreate,
    BillAccountRead,
    BillAccountSimpleRead,
    BillAccountUpdate,
    BillCategoryCreate,
    BillCategoryRead,
    BillCategorySimpleRead,
    BillCategoryUpdate,
    BillMonthSummaryRead,
    BillRecordCreate,
    BillRecordRead,
    BillRecordUpdate,
    BillSummaryCategoryRead,
    BillSummaryDailyTotalRead,
    BillTemplateCreate,
    BillTemplateGenerateResultRead,
    BillTemplateRead,
    BillTemplateUpdate,
)

__all__ = [
    "BillAccountCreate",
    "BillAccountRead",
    "BillAccountSimpleRead",
    "BillAccountUpdate",
    "BillCategoryCreate",
    "BillCategoryRead",
    "BillCategorySimpleRead",
    "BillCategoryUpdate",
    "BillMonthSummaryRead",
    "BillRecordCreate",
    "BillRecordRead",
    "BillRecordUpdate",
    "BillSummaryCategoryRead",
    "BillSummaryDailyTotalRead",
    "BillTemplateCreate",
    "BillTemplateGenerateResultRead",
    "BillTemplateRead",
    "BillTemplateUpdate",
]
